baseURL = "https://stakiran.github.io/test-hugo/"
languageCode = "ja-jp"
defaultContentLanguage = "jp"
title = "Test Hugo by stakiran"
theme = "cactus"

# for ghpages
publishDir = "docs"
# apply to use baseurl forcely about nested-dir.
canonifyurls = true